#!/usr/bin/env bash
# Configuring the Nginx server so that /redirect_me
# is redirecting to another page
apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html
old_string=\
"
	location / {
		try_files \$uri \$uri/ =404;
	}
"
new_string=\
"
	location / {
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
"
sed -i "s/$old_string/$new_string/" /etc/nginx/sites-enabled/default
if [ "$(pgrep -c nginx)" -le 0 ];
then
	service nginx start;
else
	service nginx restart;
fi
