#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html
old_string =\
"
	location / {
		try_files \$uri \$uri/ =404;
	}
"
new_string =\
"
	location / {
		try_files \$uri \$uri/ =404;
	}
	
	error_page 404 /404.html;
	location /404.html {
		root /var/www/html;
		internal;
	}
"
sudo echo "Ceci n'est pas une page" | tee /var/www/html/404.html
sed -i "s/$old_string/$new_string/" /etc/nginx/sites-enabled/default
if [ "$(pgrep -c nginx)" -le 0 ];
then
	service nginx start;
else
	service nginx restart;
fi
