#!/usr/bin/env bash
# Configuring the Nginx server so that /redirect_me
# is redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html
old_string="try_files \\\$uri \\\$uri\/ =404;"
new_string="try_files \\\$uri \\\$uri\/ =404;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\t"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
file='/etc/nginx/sites-enabled/default'
sudo sed -i '0,/'"$old_string"'/{s//'"$new_string"'/}' "$file"
if [ "$(pgrep -c nginx)" -le 0 ];
then
        sudo service nginx start;
else
        sudo service nginx restart;
fi
