#!/usr/bin/env bash
# Installing the HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy
LOAD_BALANCER="\nfrontend my_frontend\n\tbind\t0.0.0.0:80\n\tmode\thttp\n\tdefault_backend my_servers\n\nbackend my_servers\n\tbalance\troundrobin\n\tserver\t224887-web-01\t54.144.197.160:80\tcheck\n\tserver\t224887-web-02\t100.26.218.107:80\tcheck\n"
sudo sed -i "$ a\\$LOAD_BALANCER" /etc/haproxy/haproxy.cfg
sudo service haproxy start
