#!/bin/bash

while [ "$filename" != "done" ]
do
 echo "Enter a filename"
 read filename

 echo "Enter the answer to the task"
 read answer

 echo "$answer" >> $filename

 git add .
 git commit -m "$filename script done"
 git push

 echo Work done successfully
done



