#!/usr/bin/env bash
# Create a backup of the database
mysqldump --all-databases -u root --password="$1" > backup.sql
file="$(date +"%d")-$(date +"%m")-$(date +"%Y").tar.gz"
tar -czvf "$file" backup.sql
