#!/usr/bin/env bash
#Displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=':' read -r name pass uid gid inf home shell; do
  echo "The user $name is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $inf"
done < "/etc/passwd"
