#!/usr/bin/env bash
# Configure an Ubuntu server whith a 127.0.0.2 IP localhost and 8.8.8.8 IP for facebook
cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
